### ISSUE TITLE
Add GHA build flow and gem release flow

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/oscal-ruby#3]
As title.

The gem is now available : https://rubygems.org/gems/oscal

**Comment by CAMOBAP** [comment]
Done

**Comment by ronaldtse** [comment]
Thank you!

**Comment by ronaldtse** [comment]
@CAMOBAP somehow the build is failing due to rubocop-performance like this:
https://github.com/metanorma/oscal-ruby/actions/runs/4467509511/jobs/7847072173

* https://github.com/rubocop/rubocop/issues/10893#issuecomment-1439884581

Any idea?
